#!/usr/bin/env bash

if [ -z "$1" ]
then
    echo -e "\e[31mNo cluster name was provided!\e[0m"
    exit 1
fi
kubectl patch cluster $1 --type=json -p '[{"op": "replace", "path": "/status/name", "value":"Rerun"}]'
