name: macOS Install Test

on:
  schedule:
    - cron: "37 13 * * *"
  push:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Brew update / upgrade
        shell: bash
        run: |
          brew update
          brew upgrade

      - name: Run install script
        shell: bash
        run: |
          ./install.sh
