name: macOS Install Test

on:
  schedule:
    - cron: "37 13 * * *"
  push:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Brew update / upgrade
        shell: bash
        run: |
          brew update
          brew upgrade

      - name: Run install script
        shell: bash
        run: |
          ./install.sh
