name: macOS Install Test

on:
  schedule:
    - cron: "37 13 * * *"
  push:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Brew update / upgrade
        shell: bash
        run: |
          brew update
          brew upgrade

      - name: Run install script
        shell: bash
        run: |
          ./install.sh
